<?php
/**
 * PlayerConfigColors
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.6
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Api42Vb\Client\Model;

use \ArrayAccess;
use \Api42Vb\Client\ObjectSerializer;

/**
 * PlayerConfigColors Class Doc Comment
 *
 * @category Class
 * @description Player Colors Object
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlayerConfigColors implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PlayerConfig_colors';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'primary' => 'string',
        'primary_background' => 'string',
        'primary_background_color' => 'string',
        'secondary' => 'string',
        'secondary_background' => 'string',
        'secondary_background_color' => 'string',
        'tertiary' => 'string',
        'tertiary_background' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'primary' => null,
        'primary_background' => null,
        'primary_background_color' => null,
        'secondary' => null,
        'secondary_background' => null,
        'secondary_background_color' => null,
        'tertiary' => null,
        'tertiary_background' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'primary' => false,
		'primary_background' => false,
		'primary_background_color' => false,
		'secondary' => false,
		'secondary_background' => false,
		'secondary_background_color' => false,
		'tertiary' => false,
		'tertiary_background' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'primary' => 'primary',
        'primary_background' => 'primaryBackground',
        'primary_background_color' => 'primaryBackgroundColor',
        'secondary' => 'secondary',
        'secondary_background' => 'secondaryBackground',
        'secondary_background_color' => 'secondaryBackgroundColor',
        'tertiary' => 'tertiary',
        'tertiary_background' => 'tertiaryBackground'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'primary' => 'setPrimary',
        'primary_background' => 'setPrimaryBackground',
        'primary_background_color' => 'setPrimaryBackgroundColor',
        'secondary' => 'setSecondary',
        'secondary_background' => 'setSecondaryBackground',
        'secondary_background_color' => 'setSecondaryBackgroundColor',
        'tertiary' => 'setTertiary',
        'tertiary_background' => 'setTertiaryBackground'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'primary' => 'getPrimary',
        'primary_background' => 'getPrimaryBackground',
        'primary_background_color' => 'getPrimaryBackgroundColor',
        'secondary' => 'getSecondary',
        'secondary_background' => 'getSecondaryBackground',
        'secondary_background_color' => 'getSecondaryBackgroundColor',
        'tertiary' => 'getTertiary',
        'tertiary_background' => 'getTertiaryBackground'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('primary', $data ?? [], '#FFFFFF');
        $this->setIfExists('primary_background', $data ?? [], '#FFFFFF');
        $this->setIfExists('primary_background_color', $data ?? [], '#000000');
        $this->setIfExists('secondary', $data ?? [], '#FFFFFF');
        $this->setIfExists('secondary_background', $data ?? [], '#FFFFFF');
        $this->setIfExists('secondary_background_color', $data ?? [], '#FFFFFF');
        $this->setIfExists('tertiary', $data ?? [], '#FFFFFF');
        $this->setIfExists('tertiary_background', $data ?? [], '#FFFFFF');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets primary
     *
     * @return string|null
     */
    public function getPrimary()
    {
        return $this->container['primary'];
    }

    /**
     * Sets primary
     *
     * @param string|null $primary Primary color for the player
     *
     * @return self
     */
    public function setPrimary($primary)
    {
        if (is_null($primary)) {
            throw new \InvalidArgumentException('non-nullable primary cannot be null');
        }
        $this->container['primary'] = $primary;

        return $this;
    }

    /**
     * Gets primary_background
     *
     * @return string|null
     */
    public function getPrimaryBackground()
    {
        return $this->container['primary_background'];
    }

    /**
     * Sets primary_background
     *
     * @param string|null $primary_background Primary Background color for the player
     *
     * @return self
     */
    public function setPrimaryBackground($primary_background)
    {
        if (is_null($primary_background)) {
            throw new \InvalidArgumentException('non-nullable primary_background cannot be null');
        }
        $this->container['primary_background'] = $primary_background;

        return $this;
    }

    /**
     * Gets primary_background_color
     *
     * @return string|null
     */
    public function getPrimaryBackgroundColor()
    {
        return $this->container['primary_background_color'];
    }

    /**
     * Sets primary_background_color
     *
     * @param string|null $primary_background_color Primary Text of Background color for the player
     *
     * @return self
     */
    public function setPrimaryBackgroundColor($primary_background_color)
    {
        if (is_null($primary_background_color)) {
            throw new \InvalidArgumentException('non-nullable primary_background_color cannot be null');
        }
        $this->container['primary_background_color'] = $primary_background_color;

        return $this;
    }

    /**
     * Gets secondary
     *
     * @return string|null
     */
    public function getSecondary()
    {
        return $this->container['secondary'];
    }

    /**
     * Sets secondary
     *
     * @param string|null $secondary Secondary color for the player
     *
     * @return self
     */
    public function setSecondary($secondary)
    {
        if (is_null($secondary)) {
            throw new \InvalidArgumentException('non-nullable secondary cannot be null');
        }
        $this->container['secondary'] = $secondary;

        return $this;
    }

    /**
     * Gets secondary_background
     *
     * @return string|null
     */
    public function getSecondaryBackground()
    {
        return $this->container['secondary_background'];
    }

    /**
     * Sets secondary_background
     *
     * @param string|null $secondary_background Secondary Background color for the player
     *
     * @return self
     */
    public function setSecondaryBackground($secondary_background)
    {
        if (is_null($secondary_background)) {
            throw new \InvalidArgumentException('non-nullable secondary_background cannot be null');
        }
        $this->container['secondary_background'] = $secondary_background;

        return $this;
    }

    /**
     * Gets secondary_background_color
     *
     * @return string|null
     */
    public function getSecondaryBackgroundColor()
    {
        return $this->container['secondary_background_color'];
    }

    /**
     * Sets secondary_background_color
     *
     * @param string|null $secondary_background_color Secondary Text of Background color for the player
     *
     * @return self
     */
    public function setSecondaryBackgroundColor($secondary_background_color)
    {
        if (is_null($secondary_background_color)) {
            throw new \InvalidArgumentException('non-nullable secondary_background_color cannot be null');
        }
        $this->container['secondary_background_color'] = $secondary_background_color;

        return $this;
    }

    /**
     * Gets tertiary
     *
     * @return string|null
     */
    public function getTertiary()
    {
        return $this->container['tertiary'];
    }

    /**
     * Sets tertiary
     *
     * @param string|null $tertiary Tertiary color for the player
     *
     * @return self
     */
    public function setTertiary($tertiary)
    {
        if (is_null($tertiary)) {
            throw new \InvalidArgumentException('non-nullable tertiary cannot be null');
        }
        $this->container['tertiary'] = $tertiary;

        return $this;
    }

    /**
     * Gets tertiary_background
     *
     * @return string|null
     */
    public function getTertiaryBackground()
    {
        return $this->container['tertiary_background'];
    }

    /**
     * Sets tertiary_background
     *
     * @param string|null $tertiary_background Tertiary Background color for the player
     *
     * @return self
     */
    public function setTertiaryBackground($tertiary_background)
    {
        if (is_null($tertiary_background)) {
            throw new \InvalidArgumentException('non-nullable tertiary_background cannot be null');
        }
        $this->container['tertiary_background'] = $tertiary_background;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


