<?php
/**
 * DataVideoAnalyticTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Api42Vb\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataVideoAnalyticTest Class Doc Comment
 *
 * @category    Class
 * @description Video Analytics KPIs
 * @package     Api42Vb\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DataVideoAnalyticTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DataVideoAnalytic"
     */
    public function testDataVideoAnalytic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "watchtime"
     */
    public function testPropertyWatchtime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "views"
     */
    public function testPropertyViews()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
