<?php
/**
 * PlayerConfigColorsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.6
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Api42Vb\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PlayerConfigColorsTest Class Doc Comment
 *
 * @category    Class
 * @description Player Colors Object
 * @package     Api42Vb\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlayerConfigColorsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PlayerConfigColors"
     */
    public function testPlayerConfigColors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary"
     */
    public function testPropertyPrimary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary_background"
     */
    public function testPropertyPrimaryBackground()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary_background_color"
     */
    public function testPropertyPrimaryBackgroundColor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "secondary"
     */
    public function testPropertySecondary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "secondary_background"
     */
    public function testPropertySecondaryBackground()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "secondary_background_color"
     */
    public function testPropertySecondaryBackgroundColor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tertiary"
     */
    public function testPropertyTertiary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tertiary_background"
     */
    public function testPropertyTertiaryBackground()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
