<?php
/**
 * VideoDetailTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.7
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Api42Vb\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VideoDetailTest Class Doc Comment
 *
 * @category    Class
 * @description Video Detail Object
 * @package     Api42Vb\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VideoDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VideoDetail"
     */
    public function testVideoDetail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "media_tracks"
     */
    public function testPropertymediaTracks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "original_file_infos"
     */
    public function testPropertyoriginalFileInfos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quality_stream_list"
     */
    public function testPropertyqualityStreamList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quality_download_infos"
     */
    public function testPropertyqualityDownloadInfos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
