<?php
/**
 * LivesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.6
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Api42Vb\Client\Test\Api;

use \Api42Vb\Client\Configuration;
use \Api42Vb\Client\ApiException;
use \Api42Vb\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LivesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Api42Vb\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LivesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addLive
     *
     * Create a live event.
     *
     */
    public function testAddLive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addSlateByLiveIdAndName
     *
     * Upload an image file and set it as a slate for a live event.
     *
     */
    public function testAddSlateByLiveIdAndName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addThumbnailByLiveId
     *
     * Upload an image file and set it as the Thumbnail for a video.
     *
     */
    public function testAddThumbnailByLiveId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteLiveById
     *
     * Delete a live event.
     *
     */
    public function testDeleteLiveById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLiveById
     *
     * Get details of a live event.
     *
     */
    public function testGetLiveById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLives
     *
     * Retrieve a list of live events.
     *
     */
    public function testGetLives()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLivesCaptureSources
     *
     * Retrieve a list of capture sources.
     *
     */
    public function testGetLivesCaptureSources()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getScenesByLiveId
     *
     * List of the scenes in the live event.
     *
     */
    public function testGetScenesByLiveId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLiveById
     *
     * Update details of a live event.
     *
     */
    public function testUpdateLiveById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateStateOfScene
     *
     * Update the state of a scene based on its id.
     *
     */
    public function testUpdateStateOfScene()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
